package com.ledo.market.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Debt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt.dnumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String dnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt.vid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String vname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Long gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt.gname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt.ddate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Date ddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column debt.ddebt
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal ddebt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt.dnumber
     *
     * @return the value of debt.dnumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getDnumber() {
        return dnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt.dnumber
     *
     * @param dnumber the value for debt.dnumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setDnumber(String dnumber) {
        this.dnumber = dnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt.vid
     *
     * @return the value of debt.vid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt.vid
     *
     * @param vid the value for debt.vid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt.vname
     *
     * @return the value of debt.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt.vname
     *
     * @param vname the value for debt.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVname(String vname) {
        this.vname = vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt.gid
     *
     * @return the value of debt.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt.gid
     *
     * @param gid the value for debt.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt.gname
     *
     * @return the value of debt.gname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt.gname
     *
     * @param gname the value for debt.gname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt.ddate
     *
     * @return the value of debt.ddate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Date getDdate() {
        return ddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt.ddate
     *
     * @param ddate the value for debt.ddate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setDdate(Date ddate) {
        this.ddate = ddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column debt.ddebt
     *
     * @return the value of debt.ddebt
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getDdebt() {
        return ddebt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column debt.ddebt
     *
     * @param ddebt the value for debt.ddebt
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setDdebt(BigDecimal ddebt) {
        this.ddebt = ddebt;
    }
}