package com.ledo.market.entity;

import java.math.BigDecimal;
import java.util.Date;

public class FlowPayments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_payments.pnumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Integer pnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_payments.pdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Date pdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_payments.pcategory
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String pcategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_payments.psource_shop
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String psourceShop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_payments.ptrading_amount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal ptradingAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flow_payments.premainning_amount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal premainningAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_payments.pnumber
     *
     * @return the value of flow_payments.pnumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Integer getPnumber() {
        return pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_payments.pnumber
     *
     * @param pnumber the value for flow_payments.pnumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPnumber(Integer pnumber) {
        this.pnumber = pnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_payments.pdate
     *
     * @return the value of flow_payments.pdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Date getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_payments.pdate
     *
     * @param pdate the value for flow_payments.pdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_payments.pcategory
     *
     * @return the value of flow_payments.pcategory
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getPcategory() {
        return pcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_payments.pcategory
     *
     * @param pcategory the value for flow_payments.pcategory
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPcategory(String pcategory) {
        this.pcategory = pcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_payments.psource_shop
     *
     * @return the value of flow_payments.psource_shop
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getPsourceShop() {
        return psourceShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_payments.psource_shop
     *
     * @param psourceShop the value for flow_payments.psource_shop
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPsourceShop(String psourceShop) {
        this.psourceShop = psourceShop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_payments.ptrading_amount
     *
     * @return the value of flow_payments.ptrading_amount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getPtradingAmount() {
        return ptradingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_payments.ptrading_amount
     *
     * @param ptradingAmount the value for flow_payments.ptrading_amount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPtradingAmount(BigDecimal ptradingAmount) {
        this.ptradingAmount = ptradingAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flow_payments.premainning_amount
     *
     * @return the value of flow_payments.premainning_amount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getPremainningAmount() {
        return premainningAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flow_payments.premainning_amount
     *
     * @param premainningAmount the value for flow_payments.premainning_amount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPremainningAmount(BigDecimal premainningAmount) {
        this.premainningAmount = premainningAmount;
    }
}