package com.ledo.market.entity;

import java.math.BigDecimal;
import java.util.Date;

public class ProductPricing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricing.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Long gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricing.gname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String gname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricing.pold_price
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal poldPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricing.pnew_price
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal pnewPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricing.preason
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String preason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricing.pdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Date pdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_pricing.phandler
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String phandler;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing.gid
     *
     * @return the value of product_pricing.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing.gid
     *
     * @param gid the value for product_pricing.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing.gname
     *
     * @return the value of product_pricing.gname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getGname() {
        return gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing.gname
     *
     * @param gname the value for product_pricing.gname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setGname(String gname) {
        this.gname = gname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing.pold_price
     *
     * @return the value of product_pricing.pold_price
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getPoldPrice() {
        return poldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing.pold_price
     *
     * @param poldPrice the value for product_pricing.pold_price
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPoldPrice(BigDecimal poldPrice) {
        this.poldPrice = poldPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing.pnew_price
     *
     * @return the value of product_pricing.pnew_price
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getPnewPrice() {
        return pnewPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing.pnew_price
     *
     * @param pnewPrice the value for product_pricing.pnew_price
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPnewPrice(BigDecimal pnewPrice) {
        this.pnewPrice = pnewPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing.preason
     *
     * @return the value of product_pricing.preason
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getPreason() {
        return preason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing.preason
     *
     * @param preason the value for product_pricing.preason
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPreason(String preason) {
        this.preason = preason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing.pdate
     *
     * @return the value of product_pricing.pdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Date getPdate() {
        return pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing.pdate
     *
     * @param pdate the value for product_pricing.pdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPdate(Date pdate) {
        this.pdate = pdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_pricing.phandler
     *
     * @return the value of product_pricing.phandler
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getPhandler() {
        return phandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_pricing.phandler
     *
     * @param phandler the value for product_pricing.phandler
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setPhandler(String phandler) {
        this.phandler = phandler;
    }
}