package com.ledo.market.entity;

import java.util.Date;

public class ProductReturn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_return.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Long gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_return.rdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Date rdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_return.rreasong
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String rreasong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_return.rcount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Integer rcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_return.gid
     *
     * @return the value of product_return.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_return.gid
     *
     * @param gid the value for product_return.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_return.rdate
     *
     * @return the value of product_return.rdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Date getRdate() {
        return rdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_return.rdate
     *
     * @param rdate the value for product_return.rdate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setRdate(Date rdate) {
        this.rdate = rdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_return.rreasong
     *
     * @return the value of product_return.rreasong
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getRreasong() {
        return rreasong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_return.rreasong
     *
     * @param rreasong the value for product_return.rreasong
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setRreasong(String rreasong) {
        this.rreasong = rreasong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_return.rcount
     *
     * @return the value of product_return.rcount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Integer getRcount() {
        return rcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_return.rcount
     *
     * @param rcount the value for product_return.rcount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setRcount(Integer rcount) {
        this.rcount = rcount;
    }
}