package com.ledo.market.entity;

public class Roles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.rid
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.role
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    private String role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roles.permission
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    private String permission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.rid
     *
     * @return the value of roles.rid
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.rid
     *
     * @param rid the value for roles.rid
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.role
     *
     * @return the value of roles.role
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.role
     *
     * @param role the value for roles.role
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roles.permission
     *
     * @return the value of roles.permission
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    public String getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roles.permission
     *
     * @param permission the value for roles.permission
     *
     * @mbg.generated Sat May 09 23:38:42 CST 2020
     */
    public void setPermission(String permission) {
        this.permission = permission;
    }
}