package com.ledo.market.entity;

import java.math.BigDecimal;
import java.util.Date;

public class StockIn {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.inumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String inumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Long gid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String vname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.idate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Date idate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.iprice
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal iprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.ipayment
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal ipayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stock_in.icount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Integer icount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.inumber
     *
     * @return the value of stock_in.inumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getInumber() {
        return inumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.inumber
     *
     * @param inumber the value for stock_in.inumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setInumber(String inumber) {
        this.inumber = inumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.gid
     *
     * @return the value of stock_in.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Long getGid() {
        return gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.gid
     *
     * @param gid the value for stock_in.gid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setGid(Long gid) {
        this.gid = gid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.vname
     *
     * @return the value of stock_in.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.vname
     *
     * @param vname the value for stock_in.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVname(String vname) {
        this.vname = vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.idate
     *
     * @return the value of stock_in.idate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Date getIdate() {
        return idate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.idate
     *
     * @param idate the value for stock_in.idate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setIdate(Date idate) {
        this.idate = idate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.iprice
     *
     * @return the value of stock_in.iprice
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getIprice() {
        return iprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.iprice
     *
     * @param iprice the value for stock_in.iprice
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setIprice(BigDecimal iprice) {
        this.iprice = iprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.ipayment
     *
     * @return the value of stock_in.ipayment
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getIpayment() {
        return ipayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.ipayment
     *
     * @param ipayment the value for stock_in.ipayment
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setIpayment(BigDecimal ipayment) {
        this.ipayment = ipayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stock_in.icount
     *
     * @return the value of stock_in.icount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Integer getIcount() {
        return icount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stock_in.icount
     *
     * @param icount the value for stock_in.icount
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setIcount(Integer icount) {
        this.icount = icount;
    }
}