package com.ledo.market.entity;

import java.util.Date;

public class UserLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.unumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Integer unumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.udate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Date udate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.uhandler
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String uhandler;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.utype
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String utype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_log.udetail
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String udetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.unumber
     *
     * @return the value of user_log.unumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Integer getUnumber() {
        return unumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.unumber
     *
     * @param unumber the value for user_log.unumber
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setUnumber(Integer unumber) {
        this.unumber = unumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.udate
     *
     * @return the value of user_log.udate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Date getUdate() {
        return udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.udate
     *
     * @param udate the value for user_log.udate
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setUdate(Date udate) {
        this.udate = udate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.uhandler
     *
     * @return the value of user_log.uhandler
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getUhandler() {
        return uhandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.uhandler
     *
     * @param uhandler the value for user_log.uhandler
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setUhandler(String uhandler) {
        this.uhandler = uhandler;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.utype
     *
     * @return the value of user_log.utype
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getUtype() {
        return utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.utype
     *
     * @param utype the value for user_log.utype
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setUtype(String utype) {
        this.utype = utype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_log.udetail
     *
     * @return the value of user_log.udetail
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getUdetail() {
        return udetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_log.udetail
     *
     * @param udetail the value for user_log.udetail
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setUdetail(String udetail) {
        this.udetail = udetail;
    }
}