package com.ledo.market.entity;

public class UserRole {
    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.urid
     *
     * @mbg.generated Sun May 10 00:07:08 CST 2020
     */
    private Integer urid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.uid
     *
     * @mbg.generated Sun May 10 00:07:08 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.rid
     *
     * @mbg.generated Sun May 10 00:07:08 CST 2020
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.urid
     *
     * @return the value of user_role.urid
     *
     * @mbg.generated Sun May 10 00:07:08 CST 2020
     */
    public Integer getUrid() {
        return urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.urid
     *
     * @param urid the value for user_role.urid
     *
     * @mbg.generated Sun May 10 00:07:08 CST 2020
     */
    public void setUrid(Integer urid) {
        this.urid = urid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.rid
     *
     * @return the value of user_role.rid
     *
     * @mbg.generated Sun May 10 00:07:08 CST 2020
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.rid
     *
     * @param rid the value for user_role.rid
     *
     * @mbg.generated Sun May 10 00:07:08 CST 2020
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}