package com.ledo.market.entity;

import java.math.BigDecimal;

public class Vender {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Integer vid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String vname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vaddress
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String vaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vphone
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String vphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vemail
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String vemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vfax
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private String vfax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vcredit
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private Integer vcredit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vender.vsettle_account
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    private BigDecimal vsettleAccount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vid
     *
     * @return the value of vender.vid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Integer getVid() {
        return vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vid
     *
     * @param vid the value for vender.vid
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVid(Integer vid) {
        this.vid = vid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vname
     *
     * @return the value of vender.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getVname() {
        return vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vname
     *
     * @param vname the value for vender.vname
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVname(String vname) {
        this.vname = vname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vaddress
     *
     * @return the value of vender.vaddress
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getVaddress() {
        return vaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vaddress
     *
     * @param vaddress the value for vender.vaddress
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVaddress(String vaddress) {
        this.vaddress = vaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vphone
     *
     * @return the value of vender.vphone
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getVphone() {
        return vphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vphone
     *
     * @param vphone the value for vender.vphone
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVphone(String vphone) {
        this.vphone = vphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vemail
     *
     * @return the value of vender.vemail
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getVemail() {
        return vemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vemail
     *
     * @param vemail the value for vender.vemail
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVemail(String vemail) {
        this.vemail = vemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vfax
     *
     * @return the value of vender.vfax
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public String getVfax() {
        return vfax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vfax
     *
     * @param vfax the value for vender.vfax
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVfax(String vfax) {
        this.vfax = vfax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vcredit
     *
     * @return the value of vender.vcredit
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public Integer getVcredit() {
        return vcredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vcredit
     *
     * @param vcredit the value for vender.vcredit
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVcredit(Integer vcredit) {
        this.vcredit = vcredit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vender.vsettle_account
     *
     * @return the value of vender.vsettle_account
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public BigDecimal getVsettleAccount() {
        return vsettleAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vender.vsettle_account
     *
     * @param vsettleAccount the value for vender.vsettle_account
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    public void setVsettleAccount(BigDecimal vsettleAccount) {
        this.vsettleAccount = vsettleAccount;
    }
}