spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/leduo?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  config-location: classpath:mybatis/mappers/mybatis-config.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis.mappers/*Mapper.xml
server:
  port: 8088
  servlet:
    context-path: /api
