spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/leduo_market?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd
    
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/mappers/*Mapper.xml
server:
  port: 8088
  servlet:
    context-path: /api
