package com.ledo.market.mapper;

import com.ledo.market.entity.Employee;
import org.apache.ibatis.annotations.Mapper;
import org.mybatis.spring.annotation.MapperScan;

import java.util.List;

@Mapper
public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int insert(Employee record);
    List<Employee> selectAll();
    Integer delete(int eid);
}