package com.ledo.market.mapper;

import com.ledo.market.entity.ProductReturn;
import java.util.List;

public interface ProductReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_return
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int insert(ProductReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_return
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    List<ProductReturn> selectAll();
}