package com.ledo.market.mapper;

import com.ledo.market.entity.StockOut;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StockOutMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int deleteByPrimaryKey(String onumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int insert(StockOut record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    StockOut selectByPrimaryKey(String onumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    List<StockOut> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_out
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int updateByPrimaryKey(StockOut record);
}