package com.ledo.market.mapper;

import com.ledo.market.entity.StockIn;
import java.util.List;

public interface StockInMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int deleteByPrimaryKey(String inumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int insert(StockIn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    StockIn selectByPrimaryKey(String inumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    List<StockIn> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stock_in
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int updateByPrimaryKey(StockIn record);
}