package com.ledo.market.mapper;

import com.ledo.market.entity.UserLog;
import java.util.List;

public interface UserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int deleteByPrimaryKey(Integer unumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int insert(UserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    UserLog selectByPrimaryKey(Integer unumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    List<UserLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_log
     *
     * @mbg.generated Sat May 02 14:02:10 CST 2020
     */
    int updateByPrimaryKey(UserLog record);
}